export const C = {
    DYNAMO_DB: {
        GOOGLE_API_CLIENT_SECRET: 'GOOGLE_API_CLIENT_SECRET',
        GOOGLE_API_CLIENT_TOKEN: 'GOOGLE_API_CLIENT_TOKEN',
        TELEGRAM_BOT_TOKEN: 'TELEGRAM_BOT_TOKEN',
    },
    LOCAL: {
        TMP_GOOGLE_API_CLIENT_SECRET: '/tmp/TMP_GOOGLE_API_CLIENT_SECRET.json',
    }
}